# Generated by Django 2.1.3 on 2018-11-20 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_detection', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tracklet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_frame', models.IntegerField()),
                ('timeline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kino_app.Timeline')),
            ],
        ),
        migrations.AddField(
            model_name='detections',
            name='tracklet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kino_app.Tracklet'),
        ),
    ]
