# Generated by Django 2.1.3 on 2019-01-03 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FolderPath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField()),
            ],
        ),
    ]
