# Generated by Django 2.1.3 on 2019-01-03 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino_app', '0003_folderpath_abs_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folderpath',
            name='abs_path',
            field=models.TextField(),
        ),
    ]
