# Generated by Django 2.1.3 on 2019-02-04 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kino_app', '0004_auto_20190103_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detections',
            name='index_detection',
        ),
        migrations.RemoveField(
            model_name='detections',
            name='tracklet',
        ),
        migrations.AddField(
            model_name='detections',
            name='json_data',
            field=models.TextField(default='', verbose_name=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detections',
            name='path',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kino_app.FolderPath'),
        ),
    ]
