# Generated by Django 2.2.3 on 2019-07-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino_app', '0005_auto_20190204_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detections',
            name='json_data',
            field=models.TextField(),
        ),
    ]
