# Generated by Django 2.2.5 on 2019-11-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino_app', '0008_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='password',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
